### ISSUE TITLE
ERR: Seems there is no OpenSearch running on localhost:9300 - Will exit

### ISSUE THREAD

**Issue by 0x00Jeff** [flavienbwk/opensearch-docker-compose#1]
Hi, I tried following the steps in your Readme.md, I used the your .yml as is, and executed the commands as you listed them

`sudo sysctl -w vm.max_map_count=500000`

`bash generate-certs.sh`

`docker-compose up -d`

but when I execute the last command to run securityadmin, I get the following output

```
Security Admin v7

Will connect to localhost:9300

ERR: Seems there is no OpenSearch running on localhost:9300 - Will exit
```

and when visiting the address `https://localhost:5601`, not only I get an ssl error, but I also get `OpenSearch Dashboards server is not ready yet`

is this supposed to happen ? if so please suggest a fix

**Comment by flavienbwk** [comment]
Hi @0x00Jeff,

You must wait some time before running the securityadmin script (~1 to 2 minutes).

The self-signed certificate SSL error is expected, no problem.

If it doesn't work again, please send your logs.

**Comment by 0x00Jeff** [comment]
Hi, 

The solution was indeed to wait, now it's working fine

I just want to ask you if you have any idea how would I get rid of the ssl error, otherwise feel free to close the issue,

Thanks for putting up this repo

**Comment by flavienbwk** [comment]
You're welcome.

About the ssl error : self signed certificates always show a warning to clients' browser. If you want to get rid of it while still using SSL, you might be interested in Let's encrypt that provides valid authority-signed certificates. But that's out of scope for this repo.

The other consideration might be to disable SSL. But I don't recommend it. Better having a self signed certificate than no certificate.
