### ISSUE TITLE
failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]

### ISSUE THREAD

**Issue by erickertzvfc** [flavienbwk/opensearch-docker-compose#9]
This issue seems very similar to https://github.com/flavienbwk/opensearch-docker-compose/issues/1

I followed the same exact steps:

```
sudo sysctl -w vm.max_map_count=500000

bash generate-certs.sh

docker-compose up -d
```

but when I execute the last command to run securityadmin, I get the following output

```
Security Admin v7

Will connect to localhost:9300

ERR: Seems there is no OpenSearch running on localhost:9300 - Will exit
```
and when visiting the address https://localhost:5601, not only I get an ssl error, but I also get OpenSearch Dashboards server is not ready yet

The difference is that no matter how long I wait the issue does not go away. Eventually the OS containers die with the following error:

`os03_1    | java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
os03_1    | Likely root cause: OpenSearchException[Unable to read /usr/share/opensearch/config/certificates/os03/os03.key (/usr/share/opensearch/config/certificates/os03/os03.key). Please make sure this files exists and is readable regarding to permissions. Property: plugins.security.ssl.transport.pemkey_filepath]
os03_1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.checkPath(DefaultSecurityKeyStore.java:982)
os03_1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.resolve(DefaultSecurityKeyStore.java:234)
os03_1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:394)
os03_1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:255)
os03_1    | 	at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:176)
os03_1    | 	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218)
os03_1    | 	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:262)
os03_1    | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
os03_1    | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
os03_1    | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
os03_1    | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
os03_1    | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
os03_1    | 	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:781)
os03_1    | 	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:730)
os03_1    | 	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:532)
os03_1    | 	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195)
os03_1    | 	at org.opensearch.node.Node.<init>(Node.java:414)
os03_1    | 	at org.opensearch.node.Node.<init>(Node.java:341)
os03_1    | 	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
os03_1    | 	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
os03_1    | 	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
os03_1    | 	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
os03_1    | 	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
os03_1    | 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
os03_1    | 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
os03_1    | 	at org.opensearch.cli.Command.main(Command.java:101)
os03_1    | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
os03_1    | 	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
os03_1    | For complete error details, refer to the log at /usr/share/opensearch/logs/os-cluster.log
os03_1    | Killing performance analyzer process 10
os03_1    | OpenSearch exited with code 1
os03_1    | Performance analyzer exited with code 143
opensearch-docker-compose_os03_1 exited with code 0
`

**Comment by flavienbwk** [comment]
Logs say it all : `Unable to read /usr/share/opensearch/config/certificates/os03/os03.key `.

Make sure you set the right permissions for your certs files. Try a `chmod 755 -R ./certs`.

**Comment by flavienbwk** [comment]
Please reopen if having an issue again.
